name: Build APK

on:
  push:
    branches: [ "(root)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        run: |
          yes y | buildozer android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: FocusMode-APK
          path: bin/*.apk
