name: Build APK

on:
  push:
    branches: [ "(root)" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pin pip to a compatible version
        run: |
          echo "pip<24.1" > /tmp/constraints.txt
          echo "PIP_CONSTRAINT=/tmp/constraints.txt" >> $GITHUB_ENV
          python3 -m pip install "pip<24.1"

      - name: Build APK
        run: |
          yes y | buildozer android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: FocusMode-APK
          path: bin/*.apk
